services:
  - type: web
    name: life-in-weeks
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web.app:app --host 0.0.0.0 --port 10000